UPDATE `app_client_config` SET
preference = '{"generalSettings":[[{"xtype":"label","cls":"label-block-heading","text":"Marketplace Type","margin":"10 0 0 0"}],[{"layout":"hbox","allowBlank":false,"margin":"0 0 20 0","xtype":"fieldcontainer","defaults":{"flex":1},"width":300,"name":"MARKETPLACE_TYPE","disabled":false,"value":"private","items":[{"boxLabel":"Private","name":"MARKETPLACE_TYPE","inputValue":"private","checked":true,"id":"mt1"},{"boxLabel":"Third Party","name":"MARKETPLACE_TYPE","inputValue":"thirdParty","id":"mt2"}],"defaultType":"radiofield"}],[{"xtype":"label","cls":"label-block-heading","text":"Offer Type"}],[{"layout":"hbox","allowBlank":false,"margin":"0 0 20 0","xtype":"fieldcontainer","defaults":{"flex":1},"width":300,"name":"OFFER_TYPE","disabled":false,"value":"basic","items":[{"boxLabel":"Basic","name":"OFFER_TYPE","inputValue":"basic","checked":true,"id":"ot1"},{"boxLabel":"Advanced","name":"OFFER_TYPE","inputValue":"advanced","id":"ot2"}],"defaultType":"radiofield"}],[{"xtype":"label","cls":"label-block-heading","text":"Bid Settings"}],[{"boxLabel":"Allow Contract/Order Integration","xtype":"checkbox","hidden":false,"uncheckedValue":"0","name":"ALLOW_CONTRACT_INTEGRATION","inputValue":"1","disabled":false,"value":0}],[{"boxLabel":"Allow Locking of Bid Quantity","xtype":"checkbox","hidden":false,"uncheckedValue":"0","name":"IS_QUANTITY_LOCKED","inputValue":"1","disabled":false,"value":0}],[{"boxLabel":"Allow Cancellation of an Accepted Bid","xtype":"checkbox","hidden":false,"uncheckedValue":"0","name":"ALLOW_BID_CANCELLATION","inputValue":"1","disabled":false,"value":1}],[{"boxLabel":"Allow Offer Rating","xtype":"checkbox","hidden":false,"uncheckedValue":"0","name":"ALLOW_OFFER_RATING","inputValue":"1","disabled":false,"value":1}],[{"boxLabel":"Restrict Offeror Information","xtype":"checkbox","hidden":false,"uncheckedValue":"0","name":"RESTRICT_OFFEROR_INFO","inputValue":"1","disabled":false,"value":0}],[{"boxLabel":"Restrict Sharing of Personal Information","xtype":"checkbox","hidden":false,"uncheckedValue":"0","name":"RESTRICT_PERSONAL_INFO_SHARING","inputValue":"1","disabled":false,"value":0}],[{"allowBlank":true,"xtype":"textfield","margin":"2 2 2 2","fieldLabel":"Roles To Publish","width":300,"name":"ROLES_TO_PUBLISH","disabled":false,"value":null}]]}'
WHERE `app_id` = 22
AND `type` = 'GENERALSETTINGS'
AND `client_id`= '1';

UPDATE `app_client_config` SET
preference = '{"generalSettings":[[{"xtype":"label","cls":"label-block-heading","text":"Marketplace Type","margin":"10 0 0 0"}],[{"layout":"hbox","allowBlank":false,"margin":"0 0 20 0","xtype":"fieldcontainer","defaults":{"flex":1},"width":300,"name":"MARKETPLACE_TYPE","disabled":false,"value":"private","items":[{"boxLabel":"Private","name":"MARKETPLACE_TYPE","inputValue":"private","checked":true,"id":"mt1"},{"boxLabel":"Third Party","name":"MARKETPLACE_TYPE","inputValue":"thirdParty","id":"mt2"}],"defaultType":"radiofield"}],[{"xtype":"label","cls":"label-block-heading","text":"Offer Type"}],[{"layout":"hbox","allowBlank":false,"margin":"0 0 20 0","xtype":"fieldcontainer","defaults":{"flex":1},"width":300,"name":"OFFER_TYPE","disabled":false,"value":"basic","items":[{"boxLabel":"Basic","name":"OFFER_TYPE","inputValue":"basic","checked":true,"id":"ot1"},{"boxLabel":"Advanced","name":"OFFER_TYPE","inputValue":"advanced","id":"ot2"}],"defaultType":"radiofield"}],[{"xtype":"label","cls":"label-block-heading","text":"Bid Settings"}],[{"boxLabel":"Allow Contract/Order Integration","xtype":"checkbox","hidden":false,"uncheckedValue":"0","name":"ALLOW_CONTRACT_INTEGRATION","inputValue":"1","disabled":false,"value":0}],[{"boxLabel":"Allow Locking of Bid Quantity","xtype":"checkbox","hidden":false,"uncheckedValue":"0","name":"IS_QUANTITY_LOCKED","inputValue":"1","disabled":false,"value":0}],[{"boxLabel":"Allow Cancellation of an Accepted Bid","xtype":"checkbox","hidden":false,"uncheckedValue":"0","name":"ALLOW_BID_CANCELLATION","inputValue":"1","disabled":false,"value":1}],[{"boxLabel":"Allow Offer Rating","xtype":"checkbox","hidden":false,"uncheckedValue":"0","name":"ALLOW_OFFER_RATING","inputValue":"1","disabled":false,"value":1}],[{"boxLabel":"Restrict Offeror Information","xtype":"checkbox","hidden":false,"uncheckedValue":"0","name":"RESTRICT_OFFEROR_INFO","inputValue":"1","disabled":false,"value":0}],[{"boxLabel":"Restrict Sharing of Personal Information","xtype":"checkbox","hidden":false,"uncheckedValue":"0","name":"RESTRICT_PERSONAL_INFO_SHARING","inputValue":"1","disabled":false,"value":0}],[{"allowBlank":true,"xtype":"textfield","margin":"2 2 2 2","fieldLabel":"Roles To Publish","width":300,"name":"ROLES_TO_PUBLISH","disabled":false,"value":null}]]}'
WHERE `app_id` = 22
AND `type` = 'GENERALSETTINGS'
AND `client_id` IN (SELECT client_id FROM client_app_licences_mapping WHERE std_app LIKE '%"id":"22"%');

--//UNDO

UPDATE `app_client_config` SET
preference = '{"generalSettings":[[{"allowBlank":true,"margin":"2 2 2 2","xtype":"textfield","fieldLabel":"Offers: Roles To Publish","width":300,"name":"ROLES_TO_PUBLISH","disabled":false,"value":""}],[{"margin":"2 2 2 2","xtype":"checkbox","hidden":false,"fieldLabel":"Is Bid Quantity Locked","name":"IS_QUANTITY_LOCKED","disabled":false,"inputValue":"1","uncheckedValue":"0"}]]}'
WHERE `app_id` = 22
AND `type` = 'GENERALSETTINGS'
AND `client_id`= '1';

UPDATE `app_client_config` SET
preference = '{"generalSettings":[[{"allowBlank":true,"margin":"2 2 2 2","xtype":"textfield","fieldLabel":"Offers: Roles To Publish","width":300,"name":"ROLES_TO_PUBLISH","disabled":false,"value":""}],[{"margin":"2 2 2 2","xtype":"checkbox","hidden":false,"fieldLabel":"Is Bid Quantity Locked","name":"IS_QUANTITY_LOCKED","disabled":false,"inputValue":"1","uncheckedValue":"0"}]]}'
WHERE `app_id` = 22
AND `type` = 'GENERALSETTINGS'
AND `client_id` IN (SELECT client_id FROM client_app_licences_mapping WHERE std_app LIKE '%"id":"22"%');